Controllers in action
Harritone/rails-test-guru pull request #7
Opened 2021-09-10 03:47 UTC by Harritone

2021-09-10 07:19 UTC, BubuntuClu requested changes

2021-09-10 07:19 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добвь сюда опцию `shallow: true` для ресурса вопросов, посмотри как изменяться пути и адаптируй код в контроллере

2021-09-10 07:19 UTC, BubuntuClu commented on config/routes.rb
> +  post '/quizzes/:quiz_id/questions/:id', to: 'questions#destroy'
с каких пор post ведет на метод destroy? для этого есть своей метод. и зачем вообще отдельный метод делать, если он етсь в ресурсе?

2021-09-10 07:19 UTC, BubuntuClu commented on app/models/question.rb
> +  scope :by_quiz, ->(quiz) { where(quiz: quiz) }
у тебя есть ассоциация теста, не нужен этот скоуп

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @questions = Question.by_quiz(@quiz)
используй ассоциации

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
этот блок не нужен, ты не поддерживаешь формат отдачи json. все ненужно надо убрать, будет только `render inline: template `

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
аналогично и тут

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question.save!
если у тебя не будет сохранен вопрос при вызове бэнг метода, у тебя упадет приложение. у тебя нет тут блока `rescue` чтобы обработать падение. не используй бэнг методы просто так

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question.save!
если вопрос не будет сохранен, то как пользователь об этом узнает?
надо обработать ситуацию когда вопрос не сохраняется

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.destroy!
аналогичная ситуация с бэнг методом

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.permit(:body, :quiz_id)
если будешь использовать ассоциации, то тут не нужен `quiz_id`

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.new(question_params)
инициализируй объект через ассоциацию теста

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  skip_before_action :verify_authenticity_token, only: %i[create destroy]
зачем тут что-то пропускать? что тут случилось?

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :set_quiz, only: %i[index new]
для создания вопроса тест тоже нужен

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.by_quiz(params[:quiz_id]).find(params[:id])
тут надо будет изменить поиск, после добавление опции в роутинг

2021-09-10 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +class QuestionsController < ApplicationController
>Создания вопроса. Используйте шаблон с HTML формой. Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form

а где код для этого задания?

2021-09-10 07:23 UTC, Harritone commented on config/routes.rb
> +  post '/quizzes/:quiz_id/questions/:id', to: 'questions#destroy'
HTML form нам не предоставляет большого выбора, не дает нам возможность делать DELETE. Когда дойдём до представлений, исправлю. Или лучше это сделать сейчас?

2021-09-10 07:26 UTC, Harritone commented on app/controllers/questions_controller.rb
> +  skip_before_action :verify_authenticity_token, only: %i[create destroy]
В render inline для экшенов create и destroy зашита форма, и рельса нам не даёт отправить запрос, т.к. это не стандартное рельсовое представление, нет cfrs токена.

2021-09-10 07:29 UTC, Harritone commented on app/controllers/questions_controller.rb
> +class QuestionsController < ApplicationController
38 <form action="/quizzes/#{params[:quiz_id]}/questions" method="POST">
Это не то?

2021-09-11 18:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +class QuestionsController < ApplicationController
аа, ты в код экшена это зашил. нет, так делать не стоит. для этого есть вьюхи

2021-09-11 18:32 UTC, BubuntuClu commented on config/routes.rb
> +  post '/quizzes/:quiz_id/questions/:id', to: 'questions#destroy'
сейчас исправить. научишься потом менять методы для стандартных действий, и будут тебя по рукам бить. если надо потестить что-то не GET используй доп софт, который позволяет генерировать запросы. взять тот же ncat из первого урока, ты через него можешь слать запросы на свое приложение.

можно более удобное с GUI использовать, например POSTMAN

2021-09-11 18:34 UTC, BubuntuClu requested changes

2021-09-11 18:34 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @questions = Quiz.find(params[:quiz_id]).questions
before_action :set_quiz, only: %i[index new create]
у тебя ищется тест в колбэке, его не надо еще раз искать

2021-09-11 18:34 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question.save
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2021-09-11 18:34 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.new(question_params)
^ выше комментарий актуален

2021-09-11 18:34 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.permit(:body, :quiz_id)
^ выше комментарий актуален

2021-09-12 17:22 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :quiz_id)
`quiz_id` в параметрах не нужен, так как ты создаешь через ассоциацю теста вопрос

2021-09-12 23:21 UTC, merged